show user;

CREATE USER C##DORA IDENTIFIED BY 12345;

SHOW USER;

GRANT CREATE SESSION TO C##DORA;

ALTER USER C##DORA IDENTIFIED BY 1234;

CONNECT C##DORA/1234;


PASSWORD;

CREATE PROFILE C##ARIFUL LIMIT FAILED_LOGIN_ATTEMPTS 3;

ALTER USER C##DORA PROFILE C##ARIFUL;

ALTER USER C##DORA ACCOUNT LOCK ;

CONNECT C##DORA/1234;

ALTER USER C##DORA ACCOUNT UNLOCK;

CONNECT C##DORA/12;
CONNECT C##DORA/123;