show user;

CREATE profile c##random limit
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME 1
PASSWORD_GRACE_TIME 10
PASSWORD_LIFE_TIME 10
PASSWORD_REUSE_MAX 2
PASSWORD_REUSE_TIME DEFAULT;

SELECT profile FROM DBA_PROFILES;

create user c##ar IDENTIFIED by 1234;

GRANT CREATE SESSION to c##ar;

ALTER USER c##ar PROFILE c##random;

